### ISSUE TITLE
Basic Mob Health System

### ISSUE THREAD

**Issue by Acruid** [space-wizards/space-station-14-content#115]
This would be a basic health system for mobs. Nothing fancy, just something that can be used to demonstrate combat.

Requirements:
- [x] At least a HP Value from 0 to 100.
- [x] Basic Mob health states (Normal, Injured, Crit, Dead) that can be polled by other systems. These can be implemented as thresholds of the HP value.
- [x] Events raised when Healed, Damaged, or State change.
- [x] Basic HP packs that can be used on a mob to restore them. This does not need to be complex, it can literally just be an item that restores HP when used.

There already exists a damage system in Content.Server, it may be a good starting point.

This issue requires https://github.com/space-wizards/space-station-14-content/issues/42

**Comment by Injazz** [comment]
Space Station 13 doesn't feature generic health. We already got Damage Thresholds implemented, as well, as states, state change events and #143 adds healthpacks

**Comment by Acruid** [comment]
Completed in #143, closing.
