### ISSUE TITLE
You can't interact with items in your offhand

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14-content#147]
**Steps to reproduce:** take a backpack, switch hands, take an item, try to put item into backpack by clicking on backpack with item in hand. Or, take a flashlight, take battery out, with battery in hand and flashlight in offhand try to put battery back.
**What should happen:** you should be able to put an item into backpack.
**What really happens:** nothing.

**Comment by RemieRichards** [comment]
It's because the HandsGUI just has ```SpriteViews``` with no logic on them, it's not the backpack it's just the backpack's sprite.

We could maybe do with some kind of control that's a ```SpriteView``` with click functionality, a combination of a ```SpriteView``` and a ```BaseButton```.

**Comment by PJB3005** [comment]
Fixed by c27be2bf95881652857334a37fb4cf9e2fea709e
