### ISSUE TITLE
Actual item location is unchanged on pickup, but is relative to mob's location

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14-content#148]
**Step's to reproduce**: with `showbb` command try to pick up an item. 
**What's should happen**: item is placed on mob's location.
**What really happens**: showbb shows that item's bounding box (and actual location as well) still on the same place, but when character moves or rotates, it's moves and rotates too, but relatively to character it's still on the same distance/location.
For example: Trying to turn on the flashlight will light up area around actual location of flashlight, not character
![image](https://user-images.githubusercontent.com/43905364/54817720-69406780-4cb9-11e9-8018-2532af5eb73b.png)

**Comment by RemieRichards** [comment]
Fixed in https://github.com/space-wizards/space-station-14-content/commit/5b0f49bab73e4a2e6ef4271c4ef41c54ee908ccf
