### ISSUE TITLE
Worn Item's sprites are teleported to (0,0) location on unequip

### ISSUE THREAD

**Issue by Injazz** [space-wizards/space-station-14-content#149]
if unequipping items from character's inventory, their bounding box is set in actual location of the item, while sprite ~~gets under the character~~ teleported to (0,0) location, making item impossible to pick up by clicking the sprite.
![image](https://user-images.githubusercontent.com/43905364/54817867-bfada600-4cb9-11e9-9260-d73be7e598c7.png)

**Comment by RemieRichards** [comment]
Fixed in https://github.com/space-wizards/space-station-14/commit/ab1dfed25cd91602f24af69d2c06c1c8c89238d8

Just need a submodule update here.
