### ISSUE TITLE
Melee weapons

### ISSUE THREAD

**Issue by outbools** [space-wizards/space-station-14-content#16]
Following Top Priority list melee weapons are the ones which needed to make a nice demonstration.

Following Urist's [design doc:](https://docs.google.com/document/d/13CyzP6oTy8uaEftFlkqMwzOBRuygKXYcrSwR66ZnAvU/edit)

# Melee weapons
Melee weapons are held items that when used with the “interact with this location” command spawn a cone hitbox from the character in that direction for a specific time. Entities that come into contact with the cone are affected by the melee weapon (this usually means damage but can be something more exotic).

### Melee weapons have several characteristics:
- Angle and length of the cone, determining its area of effect.
- Windup time - how long it takes for the cone to appear after the command is issued.
- Cone duration time - how long the cone stays after it appears. Usually very short.
- Cooldown time - minimum time between the commands. Should usually be bigger or at least no smaller than the previous two combined.
- Damage type and value. By default, melee weapons apply that much damage of that type to Damageable entities hit.
- Possible overrides include changing what the “on hit” function does instead of damage, or changing the hitbox’s shape.

**Comment by outbools** [comment]
Silvertorch5#6128
but it sure notifies when comment is added

**Comment by outbools** [comment]
![image](https://user-images.githubusercontent.com/28573306/32995863-7c85627a-cd9c-11e7-9465-2386b9c38d36.png)
thanks pjb for decriptive concept art

**Comment by outbools** [comment]
@NeoBoyNextDoor from discord:
>Its a little "addition" to what SS13 has. I can find somewhere my edited pic... Oh wait, its not what you really can implement, because its fucking stupid if you look at it 1 time (I still have ideas for this siht), lemme try to write something more simple.(изменено)
>So, what @Saphire suggested CAN work in SS14. But instead of going "full circle" for aiming, you take an aiming system alike Mount & Blade, copy paste its direction arrows and put them at 45* angle, creating 8 directions Attack/Block system.
>And you put restrictions on such system. Like one handed can parry 1 arrow, two handed can block 3, but take more stamina with it etc etc
>But there will be problem with godlike blockers. Such fuckers can be worked around by adding "Push" or something to break block.
>I actually had idea of aiming not with mouse, but with actual arrows. But that would already fuck my shit enough. Instead, I want to add to docs something like "weapon speed cap", so you cant swing it full circle at full speed to catch all of the pokemons in one go.
>Actually, Getting a triple rock-paper-scissor melee like I did can be the best way. But that would require for such game as SS13 to become more keymap  necessity.
x3 rps is like The Culling combined with notes of Lifeweb and alot of Sword fighting games.
>First rps is Attack<- Block<-Push<- Attack
>Second is advanced movement like Grabs, Tackles and Empowered pushes (Kick). They dont affect battle frontally, they incapacitate enemy
>Third is when you get to Grab enemy: Light attacks, Spec attacks (Bite your enemy etc etc, go wild here.), Pull, Shackle (which could probably work as an some kind of unique gimmick for both grabber&grabbed, acting differently in both positions) and etc.
>Also, explosive quick draw sheath is fucking golden idea for ninja mod, why the fuck nobody suggested it.

**Comment by clusterfack** [comment]
We have *basic* melee weapons now similar to the ones described here
