### ISSUE TITLE
Basic inventory

### ISSUE THREAD

**Issue by outbools** [space-wizards/space-station-14-content#17]
Following top priority list we also need inventory for a good demonstration of features.

This is what Urist [wrote on this subject](https://docs.google.com/document/d/1ULMW0b7rfKQBqrmp_SZ2ce4GpKmfry-U5HhGtN6qCyc/edit) (consider this headcanon):

# Inventory
Mobs have several slots they can put items in, based on the organs of the mob and possibly items in other slots. These work as separate container entities. All of the slots that the mob has are shown on the UI (see the example) and can be interacted with as normal; they are always considered to be within the mob’s range. Worn items can affect the characteristics and behaviour of the mob.

One of the commands available for Container objects that hold HeldItems is “open”. It is a primary command always available regardless of the current item in the hand or a secondary command available when you have such a Container in your hand. When you open such a Container, a window pops up showing all its slots and items currently inside of them, if any. As long as the Container is within the mob’s interaction range, objects inside of it are considered within his interaction range too. The window can be closed via the close button in the corner.

Items can be dragged from inventory slots or the world map to inventory slots by clicking the LMB on the item, holding it, dragging it to the slot desired and releasing the button. If the slot can hold the item, it is moved there.

If a mob has a toolbelt equipped, it works as his hotkey bar. Each of the toolbelt’s slots is mapped to a key in the 0-9 range and by pressing that key the player controlling the mob can:
- If there’s an item in the current hand, it can go to the corresponding slot and the slot is empty, the item is put into that slot.
- If the current hand is empty, the corresponding slot has an item and the item can go in the current hand, the item is put in the current hand. 
- If there’s an item in the current hand, the corresponding slot has an item and they can swap (meaning that both slots would be able to hold the others’ items were they empty) then they swap.
- If any of these scenarios occur, that slot is marked as “last used”. By pressing a hotkey a player can quickly access the “last used” toolbelt slot using the same behaviour as above.
- Accessing the backpack can also be done by using a hotkey (“I” by default) instead of using the “open” command on it as usual.

For now, the following inventory slots should suffice. I’m including organ-based stuff but that should only be worked in when organs are in, obv - organs shouldn’t come first:

- **PDA/ID** (provided by some clothing)
- **Clothing** (provided by the body organ)
- **Toolbelt** (provided by the torso organ)
- **Ears** (provided by the head organ)
- **Mask** (provided by the head organ)
- **Hand** x2 (each provided by an arm organ)
- **Back** (provided by the torso organ)

**Comment by clusterfack** [comment]
Basic version completed
