### ISSUE TITLE
Player to entity interaction

### ISSUE THREAD

**Issue by outbools** [space-wizards/space-station-14-content#20]
[Source](https://docs.google.com/document/d/1ppet0iYMTlhqhlUwvZu452XEh2zlMjGQsKiyhsFTQos/edit)

# Player to entity interaction
A player character (PC, mob controlled by the player) can interact with the environment by pressing primary interaction mode or secondary interaction mode (LMB and RMB by default).

The primary interaction mode is an _entity-to-entity interaction mode_ - it checks the currently equipped object (if any), checks the entity clicked (based on clicking hitboxes) and, if the entity is within the PC’s reach, either uses the default command for the pair (if the button was just clicked) or gives a list of commands that are appropriate for the specific combination (if the button is held) - for example, using a wrench on a girder could give the “screw to the floor” and “disassemble” commands, with the default one being one of these.

The list of commands appears in a wheel around the mouse cursor and the player can select any of them by moving the mouse off center. Once the command is confirmed by moving the mouse in its direction and releasing the button, information about the PC, what command was chosen and what were the entities used and interacted with are sent in an event to both the entities and they act based on that.
The secondary interaction mode is an entity-to-location and entity-to-itself mode.

When the button is held, it provides a list of commands which the PC can do with the entity itself and a command for “interact with this location”; the default command (when the button is just pressed) is always “interact with this location”. For example, a gun could have the commands “shoot” (“interact with this location”) and “reload”, with the default one being “shoot”. These commands don’t check for reach.
Empty hands also have such commands, behaving just like held items in that regard. Honestly, maybe they should be held items.

The default action is always on the upper part of the wheel.

Commands are shown via icons or text or both, not sure yet.

Commands may be unavailable due to certain circumstances (a “shoot” command might be unavailable when the gun is out of ammo, primary interaction mode commands are unavailable when the object is out of the character’s reach). In these cases, the commands are greyed out on the wheel, with a message on top of them showing the reason why they’re unavailable.

**Comment by outbools** [comment]
As it was discussed in Discord, everyone agreed to divide actions on "hostile"(which are going to be area-based: swings, pierces, uppercuts, circle) and "normal". Player will have a "switch intent" key on keyboard, upon press it will change from normal "peaceful" stance to "hostile"

Example: you have a crowbar.
Help intent - peaceful stance: dismantle action, you trying to dismantle clicked entity if entity have Dismantable component
Player presses SHIFT (example for 'switch intent' key) - Player Character assumes hostiles stance, cursor becomes red, PC silhouette's outline is now red. Intent switches to harm.
Harm intent - hostile stance: attack action, PC punching shit out of arc area in front of you. Entities with Damagable component located in said arc will suffer some damage.

**Comment by hello-marmalade** [comment]
Perhaps left click for help, right click for harm - RTS style kinda?

**Comment by outbools** [comment]
@hello-marmalade you controlling only one PC and there is more then 2 actions you can do on an items in SS13. In fact, items support additional actions via verbs. Combat itself needs more then one button. Having wheel or context menu on right click is something SS13 players would want to have since they get used to it and it's intuitive for new players(because cRPGs use right click for the same purpose)
