### ISSUE TITLE
Holding and dropping items

### ISSUE THREAD

**Issue by outbools** [space-wizards/space-station-14-content#21]
[Copied from Urist's design doc:](https://docs.google.com/document/d/1ppet0iYMTlhqhlUwvZu452XEh2zlMjGQsKiyhsFTQos/edit)

# Held items

A mob has a container with X hand slots, usually 2. He can switch between them freely (using the mouse wheel? hmm). A hand slot can be empty or it can contain a held item. The item (or emptiness) in the currently selected hand is used as the “currently equipped” value for PC interaction with the environment.

The default command when using primary interaction mode with an empty hand on an item that can be held is “pick up”, and this command is only available in these circumstances. Picking up an item places it into the current hand slot.

Some items may occupy multiple slots. In that case, picking up that item will push around your inventory so the items can be in two consecutive hands.

All held items have a “drop” command in secondary interaction mode, always in the same place on the wheel (probably left part). It drops the item under the character’s feet, leaving that hand empty.

All held items also have a type tag that can be “default”, “none” or one of the specific other types. This determines in what kind of toolbelt slots it can go. “Default” can go only to non-specialised toolbelt slots, “none” can’t go to toolbelt slots and specific types can go to toolbelt slots of that type or to non-specialised slots.

**Comment by clusterfack** [comment]
We have this functionality
