### ISSUE TITLE
Basic Research System

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14-content#29]
Adding a few machines, with basic UI, that you can tell to research specific things or raise research levels. After a certain amount of time has passed with the machine functional the research will be unlocked.

**Comment by outbools** [comment]
Mine ResearchCoin.
In 26 century all scientist using Bayes's blockchain to research everything in their hands. It also consumes half of the station powernet with 20% raise in consumption each 20 minutes
