### ISSUE TITLE
Nuget Packages

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14-content#3]
The package locations are using some relative pathing, so the content solution will be unable to resolve the nuget package references until you do a build from the engine solution.

**Comment by PJB3005** [comment]
Fixable by making them relative to the solution's dir in msbuild.

**Comment by clusterfack** [comment]
Isn't that also going to make it so it downloads packages in both solutions?

**Comment by PJB3005** [comment]
No
