### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by DrCelt** [space-wizards/space-station-14-content#47]
Is there anything that needs done that I can give a hand with?

**Comment by PJB3005** [comment]
Well, do you know C#?

Also get in Discord.

**Comment by DrCelt** [comment]
I thought it was in godot

**Comment by DrCelt** [comment]
also how can I help

**Comment by DoctoreMad** [comment]
@DrCelt I have a few images I want you to review.

**Comment by Acruid** [comment]
If you want to know how you can help, come talk to us in Discord.
https://discord.gg/MwDDf6t
