### ISSUE TITLE
Script to copy scenes over to godot in engine

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/space-station-14-content#62]
Since godot cant load resources from outside of its own folder right now, we need a way to send scenes from content to the godot folder. I've been placing scenes inside resources/scenes in the content folder which people have to manually copy into godots scene folders.

What we need is a script that runs on build which copies over the scenes into the godot folder so it works with minimal coder interference

**Comment by PJB3005** [comment]
I wanna solve this by not requiring a script at all, to be honest. It should be automatically handled.

**Comment by PJB3005** [comment]
If you're on a proper operating system you can just use symlinks.

:)
