### ISSUE TITLE
Space parallax. 

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14-content#76]
Requires https://github.com/space-wizards/space-station-14/issues/600

Should be done with overlays. Might (hell, probably will) need a way to do persistent canvas items in the overlay system, which will be a can of worms to implement.

**Comment by captkirk88** [comment]
Why not use a shader to generate the starfield?  Then you can allow it to have a vector set to simulate movement.  Maybe even have it layered so you have some depth.
Sort of like what is shown in this gif http://www.html5gamedevs.com/uploads/monthly_2017_07/starfield.gif.a0b1c84afb4205aa14ee186005c7a610.gif

**Comment by PJB3005** [comment]
While using a shader is definitely possible (and perhaps easier), it's gonna be quite expensive on the GPU.
