### ISSUE TITLE
Bullets are sideways.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/space-station-14-content#86]
Shoot gun diagonally.

Bullets defy the laws of physics.

**Comment by outbools** [comment]
yeah cluster mentioned this once he made a gun and that's he can't be assed for now

**Comment by PJB3005** [comment]
That was fixed.

I probably then re-broke it.

On Jul 31, 2018 20:13, "outbools" <notifications@github.com> wrote:

yeah cluster mentioned this once he made a gun and that's he can't be assed
for now

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/space-wizards/space-station-14-content/issues/86#issuecomment-409317286>,
or mute the thread

**Comment by Acruid** [comment]
Bullet rotation works fine now, closing.
